title: "Blue Ribbon Seamless Gutter"
description: "Expert seamless gutter installation and repair serving Boyertown, Pottstown, and Montgomery and Berks Counties."
url: "https://blueribbongutters.com"
baseurl: ""
permalink: /blog/:title/

# Pages to exclude from sitemap and crawlers
defaults:
  - scope:
      path: "admin-visitors.html"
    values:
      sitemap: false
  - scope:
      path: "home2.html"
    values:
      sitemap: false
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Blog Settings
paginate: 10
paginate_path: "/blog/page:num/"

collections:
  posts:
    output: true

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
